Handle unaligned reads over breakpoints
bet4it/gdbserver pull request #3
Opened 2022-04-13 23:46 UTC by dleonard0

GDB was triggering an assert when reading data that had to be unpatched with saved breakpoint instructions.  Replaced with a byte-for-byte restoration loop.

2022-04-18 15:02 UTC, bet4it requested changes
We need a new variable in the inner for loop.

2022-04-18 15:02 UTC, bet4it commented on gdbserver.c
> +      for (i = 0; i < bp_size; i++)
```suggestion
      for (i = 0; i < bp_size; i++)
```
```suggestion
      for (size_t j = 0; j < bp_size; j++)
```

2022-04-19 00:02 UTC, dleonard0 commented on gdbserver.c
> +      for (i = 0; i < bp_size; i++)
well spotted

2022-04-19 14:30 UTC, merged

2022-04-19 14:30 UTC, bet4it commented
Great!